// Registry mapping component type names to metadata
// This will be expanded when shadcn components are installed
export const componentTypes = new Set([
  'Column',
  'Row',
  'Grid',
  'Card',
  'Tabs',
  'TabPanel',
  'Accordion',
  'AccordionItem',
  'Separator',
  'Button',
  'Input',
  'Textarea',
  'Select',
  'Checkbox',
  'RadioGroup',
  'Slider',
  'Calendar',
  'Switch',
  'Text',
  'Image',
  'Badge',
  'Avatar',
  'Progress',
  'Alert',
  'DataTable',
  'Carousel',
  'Dialog',
  'MapView',
  'Chart',
  'StarRating',
]);
